spring.application.name=emailregistration
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=spoorthireddyy26@gmail.com
spring.mail.password=rdgi gzrs dqcd ghea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom
app.mail.from=your-email@gmail.com
app.mail.from-name=Registration Team

